### ISSUE TITLE
add_contextual_help is deprecated

### ISSUE THREAD

**Issue by mchev2** [mitcho/shibboleth#18]
Below notices are displayed in debug mode.

```
Notice: has_cap was called with an argument that is deprecated since version 2.0! Usage of user levels by plugins and themes is deprecated. Use roles and capabilities instead. in /var/www/html/wp-includes/functions.php on line 3737

Notice: add_contextual_help is deprecated since version 3.3! Use get_current_screen()->add_help_tab() instead. in /var/www/html/wp-includes/functions.php on line 3573 
```

This is the line causing it - https://github.com/mitcho/shibboleth/blob/897a2140e9574a31d4fa38f23d407d91111e3476/options-admin.php#L18

**Comment by jrchamp** [comment]
In case anyone picks this up to work on it, here's what I found when I was looking:

From http://clivern.com/adding-help-tabs-in-wordpress-plugins-pages/
```
$screen = get_current_screen();
$screen->add_help_tab(...);
```
And if you want to make sure you're only adding it in the right place, it looks like you can check `$screen->id` to see if it matches the result of `add_options_page(...)`

**Comment by ck-ws** [comment]
I already fixed that in my fork, but I'm unsure how to create a pull request of only this one commit.
Maybe you can help, @jrchamp?
https://github.com/ck-ws/shibboleth/commit/3c25322218ebb5efe5e85fd89fb7ec339e363a25

**Comment by ck-ws** [comment]
Nevermind, I just created a pull request with both replaced deprecated functions :)
