### ISSUE TITLE
unusable with WordPress 4.7.1

### ISSUE THREAD

**Issue by alphram** [mitcho/shibboleth#32]
Hello,

I am trying to get this plugin to work with WordPress 4.7.1.
Unfortunately, the plugin doesn't appear the left menu of wordpress.
Can you fix this or tell me how to change the options by hand ?

Thanks in advance

**Comment by jrchamp** [comment]
It works for me. It should be under Settings -> Shibboleth. Here's the direct path: /wp-admin/options-general.php?page=shibboleth-options

If that does not work:
 * If you are using WordPress Multisite, do you have manage_network_options?
 * Otherwise, do you have manage_options capability?

**Comment by alphram** [comment]
My bad, I found it.. Thanks for your quick answer !
