### ISSUE TITLE
Valid Changes from UW-Madison?

### ISSUE THREAD

**Issue by jrchamp** [mitcho/shibboleth#4]
Greetings! I was pleased to find your official repository here, just before I went ahead with a fork from a previous version by a guy from UW-Madison.

He has a couple interesting commits on his 'uw' branch: https://github.com/bshelton229/wp-shibboleth/commits/uw

Are these valid improvements that your codebase would benefit from? Specifically:
- https://github.com/bshelton229/wp-shibboleth/commit/61e0bf7ace30e75b32f6335b59faf75f68e92f5f
- https://github.com/bshelton229/wp-shibboleth/commit/16cdcfb7f2e0d613a96a09f724bb2b98fe5ccd76
- https://github.com/bshelton229/wp-shibboleth/commit/eaede956dbc342fd2282fe423c674a256e5b04c8

Thanks! Really looking forward to using this once my entityId is approved.

**Comment by michaelryanmcneill** [comment]
Hello, thank you for reporting this issue. I am the new maintainer of the plugin and all further work on the plugin will be done in a new [GitHub repository](https://github.com/michaelryanmcneill/shibboleth/). Have these PRs been resolved/submitted @jrchamp? If not, would you be willing to submit them for consideration to the new repository?

**Comment by jrchamp** [comment]
Two of them are still relevant so I've opened pull requests. Regarding the third (double URL encoding), my reading of the `add_query_arg()` function and relevant code indicates that it should be passed in already URL-encoded (which the code already does). WordPress core made the odd decision to not URL-encode in their version of `build_query()`, so we're stuck with that for now.

Closing.
